apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: appsec
  name: trusseldraken
  namespace: appsec
spec:
  image: ${{ image }}
  port: 8080
  ingresses:
    - https://trusseldraken.intern.nav.no
  envFrom:
    - secret: threat-dragon
