apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: appsec
  name: trusseldraken
  namespace: appsec
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - https://trusseldraken.intern.nav.no
  envFrom:
    - secret: threat-dragon
  replicas:
    min: 1
    max: 1
